image:
  repository: ivan150/pedidos-api
  tag: 0.21.0
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: 24.199.78.153.nip.io
      paths:
        - path: /api
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

config:
  SPRING_PROFILES_ACTIVE: "default"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://pedido-app-postgresql:5432/pedidos?sslmode=disable"

secrets:
  DB_USERNAME: ""
  DB_PASSWORD: ""

db:
  enabled: true
  host: ""         # Si usas una DB externa, coloca el host aquí
  port: 5432
  name: pedidos
  username: pedidos
  password: pedidos123
  sslMode: disable

# Valores para la dependencia de Bitnami PostgreSQL cuando se habilite db.enabled=true
postgresql:
  auth:
    username: pedidos
    password: pedidos123
    database: pedidos
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: do-block-storage
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 192Mi
