apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pedido-app-config
  labels:
    app.kubernetes.io/name: pedido-app
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.db.enabled }}
  # URL de conexión para Spring cuando la DB está habilitada
  {{- $dbHost := default (printf "%s-postgresql" .Release.Name) .Values.db.host -}}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%v/%s?sslmode=%s" $dbHost .Values.db.port .Values.db.name .Values.db.sslMode | quote }}
  {{- end }}
