# Declarative config for Bitnami Jenkins controller
# This makes Jenkins controller resource settings reproducible via GitOps
# and avoids ad-hoc helm --set changes.

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 3Gi  # Mejora la fluidez de la UI en el nodo 4 vCPU/8Gi, dejando holgura suficiente

persistence:
  storageClass: do-block-storage
  size: 8Gi

# Para evitar errores de Multi-Attach del PVC, dejamos fijado temporalmente
# el controller al nodo donde está actualmente el volumen adjunto.
# Cuando quieras permitir que se mueva libremente, elimina este bloque.
nodeSelector:
  doks.digitalocean.com/node-pool: pool-9x07hzzwz

service:
  type: LoadBalancer
  ports:
    http: 8080
    https: 8443

# Puedes añadir tolerations/affinity si deseas aislar Jenkins en un pool específico.
# tolerations: []
# affinity: {}

extraEnvVars:
  - name: JENKINS_JAVA_OPTIONS
    value: "-Xms512m -Xmx2048m -Djenkins.install.runSetupWizard=false"
  - name: JENKINS_URL
    value: "http://jenkins.jenkins.svc.cluster.local/"
